export const US_CITIES = [
  "New York, NY", "Los Angeles, CA", "Chicago, IL", "Houston, TX", "Phoenix, AZ",
  "Philadelphia, PA", "San Antonio, TX", "San Diego, CA", "Dallas, TX", "San Jose, CA",
  "Austin, TX", "Jacksonville, FL", "Fort Worth, TX", "Columbus, OH", "Charlotte, NC",
  "San Francisco, CA", "Indianapolis, IN", "Seattle, WA", "Denver, CO", "Washington, DC",
  "Boston, MA", "El Paso, TX", "Nashville, TN", "Detroit, MI", "Oklahoma City, OK",
  "Portland, OR", "Las Vegas, NV", "Memphis, TN", "Louisville, KY", "Baltimore, MD",
  "Milwaukee, WI", "Albuquerque, NM", "Tucson, AZ", "Fresno, CA", "Sacramento, CA",
  "Kansas City, MO", "Long Beach, CA", "Mesa, AZ", "Atlanta, GA", "Colorado Springs, CO",
  "Virginia Beach, VA", "Raleigh, NC", "Omaha, NE", "Miami, FL", "Oakland, CA",
  "Minneapolis, MN", "Tulsa, OK", "Wichita, KS", "New Orleans, LA", "Arlington, TX",
  "Cleveland, OH", "Bakersfield, CA", "Tampa, FL", "Aurora, CO", "Anaheim, CA",
  "Honolulu, HI", "Santa Ana, CA", "Corpus Christi, TX", "Riverside, CA", "Lexington, KY",
  "St. Louis, MO", "Stockton, CA", "Pittsburgh, PA", "Saint Paul, MN", "Cincinnati, OH",
  "Anchorage, AK", "Henderson, NV", "Greensboro, NC", "Plano, TX", "Newark, NJ",
  "Lincoln, NE", "Orlando, FL", "Irvine, CA", "Toledo, OH", "Jersey City, NJ",
  "Chula Vista, CA", "Durham, NC", "Fort Wayne, IN", "St. Petersburg, FL", "Laredo, TX",
  "Buffalo, NY", "Madison, WI", "Lubbock, TX", "Chandler, AZ", "Scottsdale, AZ",
  "Glendale, AZ", "Reno, NV", "Norfolk, VA", "Winston-Salem, NC", "North Las Vegas, NV",
  "Gilbert, AZ", "Chesapeake, VA", "Irving, TX", "Hialeah, FL", "Garland, TX",
  "Fremont, CA", "Baton Rouge, LA", "Richmond, VA", "Boise, ID", "San Bernardino, CA",
  "Spokane, WA", "Des Moines, IA", "Tacoma, WA", "Oakland, CA", "Modesto, CA",
  "Fontana, CA", "Santa Clarita, CA", "Birmingham, AL", "Oxnard, CA", "Fayetteville, NC",
  "Moreno Valley, CA", "Rochester, NY", "Glendale, CA", "Huntington Beach, CA",
  "Salt Lake City, UT", "Grand Rapids, MI", "Amarillo, TX", "Yonkers, NY", "Aurora, IL",
  "Montgomery, AL", "Akron, OH", "Little Rock, AR", "Huntsville, AL", "Augusta, GA",
  "Port St. Lucie, FL", "Grand Prairie, TX", "Columbus, GA", "Tallahassee, FL",
  "Overland Park, KS", "Tempe, AZ", "McKinney, TX", "Mobile, AL", "Cape Coral, FL",
  "Shreveport, LA", "Frisco, TX", "Knoxville, TN", "Worcester, MA", "Brownsville, TX",
  "Vancouver, WA", "Fort Lauderdale, FL", "Sioux Falls, SD", "Ontario, CA",
  "Chattanooga, TN", "Providence, RI", "Newport News, VA", "Rancho Cucamonga, CA",
  "Santa Rosa, CA", "Oceanside, CA", "Salem, OR", "Elk Grove, CA", "Garden Grove, CA",
  "Pembroke Pines, FL", "Peoria, AZ", "Eugene, OR", "Corona, CA", "Cary, NC",
  "Springfield, MO", "Fort Collins, CO", "Jackson, MS", "Alexandria, VA", "Hayward, CA",
  "Lancaster, CA", "Lakewood, CO", "Clarksville, TN", "Palmdale, CA", "Salinas, CA",
  "Springfield, MA", "Hollywood, FL", "Pasadena, TX", "Sunnyvale, CA", "Macon, GA",
  "Kansas City, KS", "Pomona, CA", "Escondido, CA", "Killeen, TX", "Naperville, IL",
  "Joliet, IL", "Bellevue, WA", "Rockford, IL", "Savannah, GA", "Paterson, NJ",
  "Torrance, CA", "Bridgeport, CT", "Mesquite, TX", "Syracuse, NY", "Midland, TX",
  "Pasadena, CA", "Murfreesboro, TN", "Miramar, FL", "Dayton, OH", "Fullerton, CA",
  "Olathe, KS", "Orange, CA", "Thornton, CO", "Roseville, CA", "Denton, TX",
  "Waco, TX", "Surprise, AZ", "Carrollton, TX", "West Valley City, UT", "Charleston, SC",
  "Warren, MI", "Hampton, VA", "Gainesville, FL", "Visalia, CA", "Coral Springs, FL",
  "Columbia, SC", "Cedar Rapids, IA", "Sterling Heights, MI", "New Haven, CT",
  "Stamford, CT", "Concord, CA", "Kent, WA", "Santa Clara, CA", "Elizabeth, NJ",
  "Round Rock, TX", "Thousand Oaks, CA", "Lafayette, LA", "Athens, GA", "Topeka, KS",
  "Simi Valley, CA", "Fargo, ND", "Norman, OK", "Columbia, MO", "Abilene, TX",
  "Wilmington, NC", "Hartford, CT", "Victorville, CA", "Pearland, TX", "Vallejo, CA",
  "Ann Arbor, MI", "Berkeley, CA", "Allentown, PA", "Richardson, TX", "Odessa, TX",
  "Arvada, CO", "Cambridge, MA", "Sugar Land, TX", "Beaumont, TX", "Lansing, MI",
  "Evansville, IN", "Rochester, MN", "Independence, MO", "Fairfield, CA",
  "Provo, UT", "Clearwater, FL", "College Station, TX", "West Jordan, UT",
  "Carlsbad, CA", "El Monte, CA", "Murrieta, CA", "Temecula, CA", "Springfield, IL",
  "Palm Bay, FL", "Costa Mesa, CA", "Westminster, CO", "North Charleston, SC",
  "Miami Gardens, FL", "Manchester, NH", "High Point, NC", "Downey, CA",
  "Clovis, CA", "Pompano Beach, FL", "Pueblo, CO", "Elgin, IL", "Lowell, MA",
  "Antioch, CA", "West Palm Beach, FL", "Peoria, IL", "Everett, WA", "Ventura, CA",
  "Centennial, CO", "Lakeland, FL", "Gresham, OR", "Richmond, CA", "Billings, MT",
  "Inglewood, CA", "Broken Arrow, OK", "Sandy Springs, GA", "Jurupa Valley, CA",
  "Hillsboro, OR", "Waterbury, CT", "Santa Maria, CA", "Boulder, CO", "Greeley, CO",
  "Daly City, CA", "Meridian, ID", "Lewisville, TX", "Davie, FL", "West Covina, CA",
  "League City, TX", "Tyler, TX", "Norwalk, CA", "San Mateo, CA", "Green Bay, WI",
  "Wichita Falls, TX", "Sparks, NV", "Lakewood, NJ", "Burbank, CA", "Rialto, CA",
  "Allen, TX", "El Cajon, CA", "Las Cruces, NM", "Renton, WA", "Davenport, IA",
  "South Bend, IN", "Vista, CA", "Tuscaloosa, AL", "Clinton, MI", "Edinburg, TX",
  "Nampa, ID", "Carmel, IN", "Spokane Valley, WA", "San Angelo, TX", "Kenosha, WI",
  "Layton, UT", "Bellingham, WA", "Chico, CA", "Auburn, AL", "Lawrence, KS"
];